// Production, test, generated, vendored, example, and benchmark files affect analysis differently and need one consistent classification.

import 'dart:io';

/// Classifies candidate files independently from repository traversal policy.
final class SourceClassifier {
  /// Creates a stateless source classifier.
  const SourceClassifier();

  /// Whether extensionless [file] declares a recognized Lua interpreter.
  bool hasLuaShebang(File file) {
    final RandomAccessFile handle = file.openSync();
    try {
      final int length = handle.lengthSync();
      if (length == 0) return false;
      final List<int> bytes = handle.readSync(length < 256 ? length : 256);
      if (bytes.contains(0)) return false;
      final String firstLine = String.fromCharCodes(
        bytes.takeWhile((int byte) => byte != 0x0a && byte != 0x0d),
      );
      final RegExpMatch? shebang = RegExp(
        r'^#!\s*(\S+)(?:\s+(.*))?$',
      ).firstMatch(firstLine);
      if (shebang == null) return false;

      var interpreter = shebang.group(1)!;
      if (interpreter.split('/').last == 'env') {
        final List<String> arguments = (shebang.group(2) ?? '')
            .trim()
            .split(RegExp(r'\s+'))
            .where((String argument) => argument.isNotEmpty)
            .toList(growable: false);
        if (arguments.isEmpty) return false;
        final int commandIndex = arguments.first == '-S' ? 1 : 0;
        if (commandIndex >= arguments.length) return false;
        interpreter = arguments[commandIndex];
      }
      final String command = interpreter.split('/').last;
      return RegExp(
        r'^(?:lua(?:5\.[1-4])?|luajit(?:2\.\d+)?|resty)$',
      ).hasMatch(command);
    } on FileSystemException {
      return false;
    } finally {
      handle.closeSync();
    }
  }

  /// Whether [extension] conventionally denotes a binary artifact.
  bool looksBinary(String extension) => const <String>{
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.webp',
    '.bmp',
    '.ico',
    '.pdf',
    '.zip',
    '.gz',
    '.tar',
    '.jar',
    '.dll',
    '.so',
    '.dylib',
    '.exe',
    '.wasm',
  }.contains(extension);

  /// Whether [extension] denotes source unsupported by registered adapters.
  bool looksLikeUnsupportedSource(String extension) => const <String>{
    '.go',
    '.kt',
    '.kts',
    '.swift',
    '.rs',
    '.php',
    '.rb',
    '.scala',
    '.ex',
    '.exs',
    '.fs',
    '.fsx',
    '.vb',
    '.r',
    '.jl',
    '.zig',
    '.m',
    '.mm',
  }.contains(extension);

  /// Whether [relative] follows a conventional generated-source name.
  bool isGeneratedByName(String relative) {
    final String lower = relative.toLowerCase();
    final String name = lower.split('/').last;
    return name.contains('_generated.') ||
        lower.endsWith('.g.dart') ||
        lower.endsWith('.freezed.dart') ||
        lower.endsWith('.designer.cs') ||
        lower.endsWith('.generated.cs') ||
        lower.endsWith('.g.cs') ||
        lower.endsWith('.g.i.cs') ||
        lower.endsWith('.min.js') ||
        lower.endsWith('.min.css') ||
        RegExp(r'-[0-9a-f]{8,}\.(?:js|css)$').hasMatch(name) ||
        (name.startsWith('app_localizations_') && name.endsWith('.dart')) ||
        name == 'app_localizations.dart' ||
        lower.endsWith('.gen.dart') ||
        lower.endsWith('.mocks.dart') ||
        lower.endsWith('.gr.dart') ||
        lower.endsWith('/tree_sitter/parser.h') ||
        lower.endsWith('/tree_sitter/alloc.h') ||
        lower.endsWith('/tree_sitter/array.h');
  }

  /// Whether the start of [file] declares generated provenance.
  bool hasGeneratedHeader(File file) {
    final RandomAccessFile handle = file.openSync();
    try {
      final int length = handle.lengthSync();
      final List<int> bytes = handle.readSync(length < 4096 ? length : 4096);
      final String header = String.fromCharCodes(bytes).toLowerCase();
      return RegExp(
            r'^\s*(?://|/\*)\s*(?:generated code with\b|do not change[,;:]?\s+this code is generated\b)',
          ).hasMatch(header) ||
          header.contains('generated code - do not modify') ||
          (header.contains('automatically generated') &&
              header.contains('do not modify')) ||
          (header.contains('do not edit') &&
              (header.contains('autogenerated') ||
                  header.contains('auto-generated'))) ||
          header.contains('file generated from ') ||
          header.contains('automatically generated code do not modify') ||
          header.contains('generated file - do not edit') ||
          header.contains('generated file. do not edit') ||
          header.contains('auto generated file, do not edit') ||
          header.contains('this class is generated.') ||
          header.contains('this file is generated.') ||
          header.contains('generated by:javacc') ||
          (header.contains('generated by ') &&
              header.contains('do not edit')) ||
          (header.contains('#include "tree_sitter/parser.h"') &&
              header.contains('#define language_version ') &&
              header.contains('#define state_count ')) ||
          header.contains('//{{no_dependencies}}') ||
          header.contains("no linting because it's generated code") ||
          header.contains('scanner generated by flex') ||
          (header.contains('antlr generated code') &&
              header.contains('do not edit')) ||
          (header.contains('generated from ') &&
              header.contains(' by antlr ')) ||
          (header.contains('emscripten bindings') &&
              header.contains('eslint-disable') &&
              header.contains('@ts-nocheck')) ||
          header.contains('@generated');
    } finally {
      handle.closeSync();
    }
  }

  /// Whether [file] has the density and size of a minified web bundle.
  bool isMinifiedBundle(File file, String extension) {
    if (extension != '.js' && extension != '.css') return false;
    final RandomAccessFile handle = file.openSync();
    try {
      final int length = handle.lengthSync();
      if (length < 2 * 1024) return false;
      final int sampleLength = length < 64 * 1024 ? length : 64 * 1024;
      final List<int> sample = handle.readSync(sampleLength);
      var lines = 1;
      var currentLine = 0;
      var longestLine = 0;
      for (final int byte in sample) {
        if (byte == 10) {
          lines++;
          if (currentLine > longestLine) longestLine = currentLine;
          currentLine = 0;
        } else {
          currentLine++;
        }
      }
      if (currentLine > longestLine) longestLine = currentLine;
      if (longestLine >= 2000) return true;
      if (length >= 20 * 1024 && sampleLength ~/ lines >= 500) return true;
      if (extension == '.js' && length >= 1024 * 1024) {
        final String source = String.fromCharCodes(sample);
        return source.contains('var __defProp = Object.defineProperty') &&
            source.contains('var __copyProps =');
      }
      return false;
    } finally {
      handle.closeSync();
    }
  }
}
